// museaal.ee — "Art by mood", the free-text reader.
//
// A Cloudflare Worker. A visitor's sentence, in Estonian or English, comes in; Claude
// Haiku picks the words from the catalogue's mood vocabulary that best describe the
// pictures they are after; the words go back to the page, which ranks the pictures
// itself from the scores it already has. Nothing but the sentence leaves the visitor's
// browser, and nothing is stored.
//
// GENERATED by build_mood.py -- do not edit; from data/moods.json: edit worker/template.js, not
// worker/mood-worker.js. After a change to the vocabulary, paste mood-worker.js into
// the Worker again (worker/README.md).
//
// A second door, POST /ask, is the "Find a work" page's assistant: the conversation so far
// comes in, and Claude answers with a short reply and the search it implies -- words from
// the same vocabulary, a kind, a size and a budget. The page picks the works for sale
// itself from those, and shows them under the reply. Nothing is stored here either.
//
// Needs one secret, ANTHROPIC_API_KEY (Settings > Variables and Secrets).
// Calls the Messages API with fetch: the dashboard's editor takes one file, no build step.

const WORDS = ["solemn", "serene", "contemplative", "melancholy", "lonely", "nostalgic", "tender", "intimate", "joyful", "playful", "festive", "romantic", "dreamy", "mysterious", "eerie", "anxious", "gloomy", "dramatic", "heroic", "bright", "dark", "sunny", "golden", "twilight", "moonlit", "misty", "vivid", "muted", "warm", "cold", "stormy", "still", "wintry", "spring", "summery", "autumnal", "hopeful", "cosy", "sacred", "majestic", "fragile", "sensual", "innocent", "energetic", "proud", "elegant", "lively", "empty", "spiritual", "idyllic", "wild", "harsh", "angry", "abstract", "expressive", "decorative", "simple", "ornate", "rustic", "modern", "sea", "lake", "river", "forest", "trees", "fields", "garden", "mountains", "sky", "village", "city", "harbour", "church", "interior", "portrait", "children", "family", "work", "music", "dance", "horses", "animals", "birds", "flowers", "stilllife", "boats"];
const MODEL = "claude-haiku-4-5";
const ORIGINS = ["https://museaal.ee", "https://www.museaal.ee"];
const PER_MINUTE = 20;          // requests per visitor per minute, per Worker instance (both doors)

const SYSTEM = "You match a visitor's words to a museum's picture search. The museum has scored every picture in " +
  "its collection of Estonian art against a fixed list of words: moods, light, colour, season and weather, and " +
  "subjects. Read what the visitor wrote, in Estonian or English, and pick the words from the list that best " +
  "describe the pictures they are looking for, most important first: one to five words. Read the feeling behind " +
  "the words as well as the literal subjects. For the kind of work, answer 'keep' unless the visitor names one: " +
  "'paint' if they ask for paintings, 'paper' for drawings, prints or sketches, 'all' if they ask for anything " +
  "including sculpture. Words: " + WORDS.join(", ");

const SCHEMA = {
  type: "object",
  properties: {
    words: { type: "array", items: { type: "string", enum: WORDS } },
    kind: { type: "string", enum: ["keep", "paint", "paper", "all"] },
  },
  required: ["words", "kind"],
  additionalProperties: false,
};

const SYSTEM_ASK = "You are the assistant on museaal.ee, a catalogue of Estonian art. On this page visitors look for a " +
  "work to buy among the several thousand works the catalogue's galleries have for sale now, at asking prices from " +
  "tens of euros to tens of thousands (most paintings between a few hundred and a few thousand). Each turn you write a short reply and fill in a search; " +
  "the page picks the works from your search and shows them under your reply. You do not see them before they are shown, " +
  "so never name or describe a particular work or artist, and never say what is available or what things cost; earlier turns may note what was shown.\n\n" +
  "Reply in one to three short sentences, warm and plain, never pushy. " +
  "Help them find out what they want: the place it will hang (which sets the size), the budget, and the mood or subject. " +
  "Ask one question at a time and only when it would change the search. As soon as there is anything to go on, search " +
  "(show: true) and end with the one short question that would narrow it most. Set show to false only when there is nothing to " +
  "search on yet or the visitor is just saying thanks or goodbye.\n\n" +
  "The search. words: up to five from the list below, most important first, for the mood, light, colour, season and " +
  "subject they are after; read the feeling behind what they say (a bedroom: serene, tender; an office: calm, simple). " +
  "kind: 'paint' for paintings, 'paper' for prints, drawings and watercolours, 'sculpture', 'photo', or 'any'. " +
  "size: 'small' up to 40 cm (a shelf, a hallway, a gift), 'medium' 40-100 cm (above a desk, a bed, a dresser), " +
  "'large' over 100 cm (a living-room wall, above a sofa), 'any' if unknown. budget_max and budget_min in euros, " +
  "0 for none ('under 500': max 500; 'around 1000': 700 and 1300; 'not more than two thousand': max 2000). " +
  "Keep what earlier turns established unless the visitor changes it.\n\n" +
  "Prices, delivery, framing and how to buy are the gallery's: each work links to its page. Do not promise discounts, " +
  "availability or anything about a work's value as an investment. If asked something else, answer in a sentence and " +
  "come back to the search. Words: " + WORDS.join(", ");

const SCHEMA_ASK = {
  type: "object",
  properties: {
    reply: { type: "string" },
    show: { type: "boolean" },
    words: { type: "array", items: { type: "string", enum: WORDS } },
    kind: { type: "string", enum: ["any", "paint", "paper", "sculpture", "photo"] },
    size: { type: "string", enum: ["any", "small", "medium", "large"] },
    budget_min: { type: "integer" },
    budget_max: { type: "integer" },
  },
  required: ["reply", "show", "words", "kind", "size", "budget_min", "budget_max"],
  additionalProperties: false,
};

// a photo of the visitor's room: where on the walls a work could hang, and how big that is. The
// model marks the empty areas and one object of known size (the "ruler"); the centimetres are
// worked out here from the pixels -- it places things in a picture better than it does sums
const CORNERS = ["tl_x", "tl_y", "tr_x", "tr_y", "br_x", "br_y", "bl_x", "bl_y"];
const WALL = {
  type: "object",
  properties: Object.assign(Object.fromEntries(CORNERS.map(k => [k, { type: "integer" }])),
    { width_cm: { type: "integer" }, height_cm: { type: "integer" }, where: { type: "string" } }),
  required: [...CORNERS, "width_cm", "height_cm", "where"],
  additionalProperties: false,
};
const SCHEMA_ROOM = JSON.parse(JSON.stringify(SCHEMA_ASK));
Object.assign(SCHEMA_ROOM.properties, {
  room: { type: "string" },
  walls: { type: "array", items: WALL },
  ruler: { type: "object", properties: { object: { type: "string" }, x1: { type: "integer" }, y1: { type: "integer" },
    x2: { type: "integer" }, y2: { type: "integer" }, cm: { type: "integer" } },
    required: ["object", "x1", "y1", "x2", "y2", "cm"], additionalProperties: false },
});
const LINE = { type: "object", properties: { x1: { type: "integer" }, y1: { type: "integer" }, x2: { type: "integer" }, y2: { type: "integer" } },
  required: ["x1", "y1", "x2", "y2"], additionalProperties: false };
SCHEMA_ROOM.properties.lines = { type: "array", items: LINE };
SCHEMA_ROOM.required.push("room", "walls", "ruler", "lines");
const ROOM = (w, h) => "The visitor's last message comes with a photo of their room, " + w + " x " + h + " pixels (x from the left, " +
  "y from the top). Find up to three empty areas of wall where a picture could hang: plain wall with nothing on it, typically " +
  "above a sofa, bed, desk or sideboard, never over a window, door, mirror, shelf, radiator or TV. For each, give the four corners " +
  "of the empty area in pixels (top-left, top-right, bottom-right, bottom-left), keeping a margin from furniture, the ceiling " +
  "and corners. Follow the wall's perspective: the area's top and bottom edges run parallel to the wall's own horizontal lines " +
  "in the photo (the skirting board, the ceiling line, the top of the sofa, a window frame), so in a photo taken at an angle " +
  "the area is a trapezoid whose far side is shorter, not a rectangle; its left and right edges stay vertical. Estimate its width and height in cm; and say in a few words where it is " +
  "('above the sofa'). Most promising area first. Also give a ruler: one horizontal edge of an object of known size against the " +
  "same wall -- the width of a door (80 cm) if one is visible, else a sofa, bed, window or radiator -- its two end points in " +
  "pixels and its real length in cm. Also give lines: two edges that are level in the room and run along the same wall as " +
  "the first area -- the skirting board, the ceiling line, the top of the sofa, a shelf or window frame -- each by two end points " +
  "as far apart as the photo shows; the page takes the wall's perspective from them. Set room to the kind of room in a word or two. Pick the search words from the room's " +
  "colours, light and style, and set size from the largest area. In the reply, say briefly what you see and what would suit " +
  "the space, and show works (show: true). Say nothing about any people in the photo.";
// the wall's perspective from two of its level lines: they meet at its vanishing point (or are parallel,
// in a photo taken straight on). Each area's top and bottom edges are turned to run towards it, about the
// area's middle; an area the lines would turn inside out keeps the model's own corners
function perspective(q, L) {
  if (!Array.isArray(L) || L.length < 2) return q;
  const [a, b] = L, d = (a.x1 - a.x2) * (b.y1 - b.y2) - (a.y1 - a.y2) * (b.x1 - b.x2);
  const xl = (q[0][0] + q[3][0]) / 2, xr = (q[1][0] + q[2][0]) / 2, xm = (xl + xr) / 2;
  const yt = (q[0][1] + q[1][1]) / 2, yb = (q[3][1] + q[2][1]) / 2;
  let at;
  if (Math.abs(d) < 1e-6 * Math.max(1, Math.abs(a.x1 - a.x2) * Math.abs(b.x1 - b.x2))) {
    const s = ((a.y2 - a.y1) / (a.x2 - a.x1 || 1) + (b.y2 - b.y1) / (b.x2 - b.x1 || 1)) / 2;
    at = (y, x) => y + s * (x - xm);
  } else {
    const p = a.x1 * a.y2 - a.y1 * a.x2, r = b.x1 * b.y2 - b.y1 * b.x2;
    const vx = (p * (b.x1 - b.x2) - (a.x1 - a.x2) * r) / d, vy = (p * (b.y1 - b.y2) - (a.y1 - a.y2) * r) / d;
    if (vx > xl - 50 && vx < xr + 50) return q;           // a vanishing point inside the area: the lines are wrong
    at = (y, x) => y + (vy - y) * (x - xm) / (vx - xm);
  }
  const n = [[xl, at(yt, xl)], [xr, at(yt, xr)], [xr, at(yb, xr)], [xl, at(yb, xl)]];
  const hl = n[3][1] - n[0][1], hr = n[2][1] - n[1][1];
  if (!(hl > 10 && hr > 10 && hl / hr > 0.4 && hl / hr < 2.5)) return q;
  return n.map(([x, y]) => [Math.round(x), Math.round(y)]);
}

// pixels to centimetres with the ruler; the model's own estimate where the ruler is unusable
function walls(out, w, h) {
  const R = out.ruler || {}, pxcm = R.cm >= 20 ? Math.hypot(R.x2 - R.x1, R.y2 - R.y1) / R.cm : 0;
  const len = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]);
  return (out.walls || []).slice(0, 3).map(x => {
    const q = perspective([[x.tl_x, x.tl_y], [x.tr_x, x.tr_y], [x.br_x, x.br_y], [x.bl_x, x.bl_y]], out.lines)
      .map(([a, b]) => [Math.max(0, Math.min(w, a | 0)), Math.max(0, Math.min(h, b | 0))]);
    let wc = (len(q[0], q[1]) + len(q[3], q[2])) / 2, hc = (len(q[0], q[3]) + len(q[1], q[2])) / 2;
    if (wc < 10 || hc < 10) return null;
    if (pxcm >= 0.2 && pxcm <= 30 && wc / pxcm >= 20 && wc / pxcm <= 1000) { wc /= pxcm; hc /= pxcm; }
    else { wc = x.width_cm; hc = x.height_cm; }
    if (!(wc >= 30 && hc >= 30)) return null;           // a strip under the ceiling is no place for a picture
    return { q, w_cm: Math.round(wc), h_cm: Math.round(hc), where: String(x.where || "").slice(0, 80) };
  }).filter(Boolean);
}

// the conversation as the page sends it: user first, turns alternating, short
function conversation(body) {
  const m = Array.isArray(body && body.messages) ? body.messages.slice(-12) : [];
  const out = [];
  for (const x of m) {
    const role = x && x.role === "assistant" ? "assistant" : "user";
    const text = String((x && x.content) || "").replace(/\s+/g, " ").trim().slice(0, role === "user" ? 400 : 900);
    if (!text) continue;
    if (out.length && out[out.length - 1].role === role) out[out.length - 1].content += " " + text;
    else out.push({ role, content: text });
  }
  while (out.length && out[0].role !== "user") out.shift();
  return out.length && out[out.length - 1].role === "user" ? out : [];
}

// Estonian replies come from Sonnet, whose Estonian is much better than Haiku's (about twice the
// price a reply): thinking off (between_tools, Sonnet 5.5 only), low effort, and Anthropic's
// server-side fallback, which re-runs a mistaken safety decline on another model
const SONNET = "claude-sonnet-5-5";
async function claude(env, system, messages, schema, max_tokens, model = MODEL) {
  const sonnet = model === SONNET;
  const headers = { "x-api-key": env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" };
  const body = { model, max_tokens, system, messages, output_config: { format: { type: "json_schema", schema } } };
  if (sonnet) {
    headers["anthropic-beta"] = "server-side-fallback-2026-07-01";
    Object.assign(body, { thinking: { type: "between_tools" }, fallbacks: "default" });
    body.output_config.effort = "low";
  }
  const r = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers, body: JSON.stringify(body) });
  if (!r.ok) throw new Error("The reader answered " + r.status + ".");
  const m = await r.json();
  if (m.stop_reason === "refusal") return null;
  // after a fallback, only the blocks past the last "fallback" marker are the answer
  const c = m.content || [], at = c.map(b => b.type).lastIndexOf("fallback");
  return JSON.parse(c.slice(at + 1).filter(b => b.type === "text").map(b => b.text).join(""));
}

const ET = /[õäöüšž]|\b(ja|ning|mis|midagi|kas|tahan|otsin|pilt|pildi|maal|maali|seinale|seina|alla|umbes|kuni|tere|aitäh|väike|suur|tuppa|kingituseks|eurot?)\b/i;
const EN = /\b(the|a|an|for|and|something|want|looking|painting|picture|print|wall|under|around|about|hi|hello|thanks|room|gift|my)\b/i;
function langOf(text, page) {
  const et = ET.test(text), en = EN.test(text);
  return et && !en ? "et" : en && !et ? "en" : page === "et" ? "et" : "en";
}

async function ask(body, env, reply) {
  const messages = conversation(body);
  if (!messages.length) return reply({ error: "Nothing to read." }, 400);
  let out;
  // the reply's language is decided here, not left to the model (it drifted): the visitor's last
  // message if it reads as one language, else the page's
  const et = langOf(messages[messages.length - 1].content, body.lang) === "et";
  // a photo: a JPEG the page has shrunk (and so stripped of its location data), on the last message only
  const img = typeof body.image === "string" && body.image.length < 4000000 && /^[A-Za-z0-9+/=]+$/.test(body.image) ? body.image : "";
  const w = Math.round(Number(body.w) || 0), h = Math.round(Number(body.h) || 0), photo = !!img && w >= 100 && h >= 100 && w <= 4000 && h <= 4000;
  if (photo) {
    const last = messages[messages.length - 1];
    last.content = [{ type: "image", source: { type: "base64", media_type: "image/jpeg", data: img } }, { type: "text", text: last.content }];
  }
  const system = SYSTEM_ASK + "\n\n" + (et
    ? "Reply in Estonian: everyday spoken Estonian, addressing the visitor as 'sina', no exclamations."
    : "Reply in English.") + (photo ? "\n\n" + ROOM(w, h) : "");
  try { out = await claude(env, system, messages, photo ? SCHEMA_ROOM : SCHEMA_ASK, photo ? 1500 : et ? 800 : 400, photo || et ? SONNET : MODEL); }
  catch (e) { return reply({ error: String(e.message || "The assistant could not be reached.") }, 502); }
  if (!out) return reply({ reply: "", show: false, words: [], kind: "any", size: "any", budget_min: 0, budget_max: 0 });
  const int = v => Math.max(0, Math.min(10000000, Math.round(Number(v) || 0)));
  return reply({
    ...(photo ? { room: String(out.room || "").slice(0, 40), walls: walls(out, w, h) } : {}),
    reply: String(out.reply || "").slice(0, 600),
    show: !!out.show,
    words: [...new Set((out.words || []).filter(w => WORDS.includes(w)))].slice(0, 5),
    kind: ["paint", "paper", "sculpture", "photo"].includes(out.kind) ? out.kind : "any",
    size: ["small", "medium", "large"].includes(out.size) ? out.size : "any",
    budget_min: int(out.budget_min), budget_max: int(out.budget_max),
  });
}

const seen = new Map();          // visitor -> times of their recent searches
function tooMany(ip) {
  const now = Date.now(), t = (seen.get(ip) || []).filter(x => now - x < 60000);
  t.push(now); seen.set(ip, t);
  if (seen.size > 5000) seen.clear();
  return t.length > PER_MINUTE;
}

const photos = new Map();        // visitor -> times of their recent photos: 6 a minute
function tooManyPhotos(ip) {
  const now = Date.now(), t = (photos.get(ip) || []).filter(x => now - x < 60000);
  t.push(now); photos.set(ip, t);
  if (photos.size > 5000) photos.clear();
  return t.length > 6;
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";
    const ok = ORIGINS.includes(origin);
    const cors = {
      "Access-Control-Allow-Origin": ok ? origin : ORIGINS[0],
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Access-Control-Max-Age": "86400",
      "Vary": "Origin",
    };
    const reply = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
    if (request.method !== "POST" || !ok) return reply({ error: "This service answers museaal.ee only." }, 403);
    if (tooMany(request.headers.get("CF-Connecting-IP") || "?")) return reply({ error: "Too many searches; wait a minute." }, 429);

    let body = {};
    try { body = await request.json(); } catch (e) {}
    if (!env.ANTHROPIC_API_KEY) return reply({ error: "The service is not set up." }, 503);
    if (new URL(request.url).pathname === "/ask") {
      if (body.image && tooManyPhotos(request.headers.get("CF-Connecting-IP") || "?")) return reply({ error: "Too many photos; wait a minute." }, 429);
      return ask(body, env, reply);
    }

    let q = "";
    try { q = String(body.q || "").replace(/\s+/g, " ").trim().slice(0, 200); } catch (e) {}
    if (!q) return reply({ error: "Nothing to read." }, 400);

    let r;
    try {
      r = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "x-api-key": env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" },
        body: JSON.stringify({
          model: MODEL, max_tokens: 200, system: SYSTEM,
          messages: [{ role: "user", content: q }],
          output_config: { format: { type: "json_schema", schema: SCHEMA } },
        }),
      });
    } catch (e) { return reply({ error: "The reader could not be reached." }, 502); }
    if (!r.ok) return reply({ error: "The reader answered " + r.status + "." }, 502);

    const m = await r.json();
    if (m.stop_reason === "refusal") return reply({ words: [], kind: "keep" });
    let out;
    try { out = JSON.parse((m.content || []).filter(b => b.type === "text").map(b => b.text).join("")); }
    catch (e) { return reply({ error: "The reader's answer was unreadable." }, 502); }
    const words = [...new Set((out.words || []).filter(w => WORDS.includes(w)))].slice(0, 5);
    const kind = ["paint", "paper", "all"].includes(out.kind) ? out.kind : "keep";
    return reply({ words, kind });
  },
};
