// museaal.ee — "Art by mood", the free-text reader.
//
// A Cloudflare Worker. A visitor's sentence, in Estonian or English, comes in; Claude
// Haiku picks the words from the catalogue's mood vocabulary that best describe the
// pictures they are after; the words go back to the page, which ranks the pictures
// itself from the scores it already has. Nothing but the sentence leaves the visitor's
// browser, and nothing is stored.
//
// GENERATED by build_mood.py -- do not edit; from data/moods.json: edit worker/template.js, not
// worker/mood-worker.js. After a change to the vocabulary, paste mood-worker.js into
// the Worker again (worker/README.md).
//
// Needs one secret, ANTHROPIC_API_KEY (Settings > Variables and Secrets).
// Calls the Messages API with fetch: the dashboard's editor takes one file, no build step.

const WORDS = ["solemn", "serene", "contemplative", "melancholy", "lonely", "nostalgic", "tender", "intimate", "joyful", "playful", "festive", "romantic", "dreamy", "mysterious", "eerie", "anxious", "gloomy", "dramatic", "heroic", "bright", "dark", "sunny", "golden", "twilight", "moonlit", "misty", "vivid", "muted", "warm", "cold", "stormy", "still", "wintry", "spring", "summery", "autumnal", "hopeful", "cosy", "sacred", "majestic", "fragile", "sensual", "innocent", "energetic", "proud", "elegant", "lively", "empty", "spiritual", "idyllic", "wild", "harsh", "angry", "abstract", "expressive", "decorative", "simple", "ornate", "rustic", "modern", "sea", "lake", "river", "forest", "trees", "fields", "garden", "mountains", "sky", "village", "city", "harbour", "church", "interior", "portrait", "children", "family", "work", "music", "dance", "horses", "animals", "birds", "flowers", "stilllife", "boats"];
const MODEL = "claude-haiku-4-5";
const ORIGINS = ["https://museaal.ee", "https://www.museaal.ee"];
const PER_MINUTE = 20;          // searches per visitor per minute, per Worker instance

const SYSTEM = "You match a visitor's words to a museum's picture search. The museum has scored every picture in " +
  "its collection of Estonian art against a fixed list of words: moods, light, colour, season and weather, and " +
  "subjects. Read what the visitor wrote, in Estonian or English, and pick the words from the list that best " +
  "describe the pictures they are looking for, most important first: one to five words. Read the feeling behind " +
  "the words as well as the literal subjects. For the kind of work, answer 'keep' unless the visitor names one: " +
  "'paint' if they ask for paintings, 'paper' for drawings, prints or sketches, 'all' if they ask for anything " +
  "including sculpture. Words: " + WORDS.join(", ");

const SCHEMA = {
  type: "object",
  properties: {
    words: { type: "array", items: { type: "string", enum: WORDS } },
    kind: { type: "string", enum: ["keep", "paint", "paper", "all"] },
  },
  required: ["words", "kind"],
  additionalProperties: false,
};

const seen = new Map();          // visitor -> times of their recent searches
function tooMany(ip) {
  const now = Date.now(), t = (seen.get(ip) || []).filter(x => now - x < 60000);
  t.push(now); seen.set(ip, t);
  if (seen.size > 5000) seen.clear();
  return t.length > PER_MINUTE;
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";
    const ok = ORIGINS.includes(origin);
    const cors = {
      "Access-Control-Allow-Origin": ok ? origin : ORIGINS[0],
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Access-Control-Max-Age": "86400",
      "Vary": "Origin",
    };
    const reply = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
    if (request.method !== "POST" || !ok) return reply({ error: "This service answers museaal.ee only." }, 403);
    if (tooMany(request.headers.get("CF-Connecting-IP") || "?")) return reply({ error: "Too many searches; wait a minute." }, 429);

    let q = "";
    try { q = String((await request.json()).q || "").replace(/\s+/g, " ").trim().slice(0, 200); } catch (e) {}
    if (!q) return reply({ error: "Nothing to read." }, 400);
    if (!env.ANTHROPIC_API_KEY) return reply({ error: "The service is not set up." }, 503);

    let r;
    try {
      r = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "x-api-key": env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" },
        body: JSON.stringify({
          model: MODEL, max_tokens: 200, system: SYSTEM,
          messages: [{ role: "user", content: q }],
          output_config: { format: { type: "json_schema", schema: SCHEMA } },
        }),
      });
    } catch (e) { return reply({ error: "The reader could not be reached." }, 502); }
    if (!r.ok) return reply({ error: "The reader answered " + r.status + "." }, 502);

    const m = await r.json();
    if (m.stop_reason === "refusal") return reply({ words: [], kind: "keep" });
    let out;
    try { out = JSON.parse((m.content || []).filter(b => b.type === "text").map(b => b.text).join("")); }
    catch (e) { return reply({ error: "The reader's answer was unreadable." }, 502); }
    const words = [...new Set((out.words || []).filter(w => WORDS.includes(w)))].slice(0, 5);
    const kind = ["paint", "paper", "all"].includes(out.kind) ? out.kind : "keep";
    return reply({ words, kind });
  },
};
